INLINE_DELIMITER = "__^__^__^__"
NEWLINE_DELIMITER = "__n__n__n__\n"
END_OF_INPUT = "__T__eoi__eoi__T__"
EPSILON = "__epsilon__epsilon__epsilon__"
REJECT = "ACTION FOR THIS TRANSITION IS NOT DEFINED"
MOVE = "action==move"
PUT = "action==put"
ACCEPT = "action==accept"
REDUCT = "action==reduct"
NODE = "type_is_node"
LEAF = "type_is_leaf"
LR_TABLE_FILE = "/home/filip/Work/FER/5_semestar/ppj/labosi/yacc/analizator/LR_table.txt"
REDUCTIONS_FILE = "/home/filip/Work/FER/5_semestar/ppj/labosi/yacc/analizator/reductions.txt"