INLINE_DELIMITER = " "
NEWLINE_DELIMITER = "\n"
END_OF_INPUT = "T"
EPSILON = "$"
REJECT = "ACTION FOR THIS TRANSITION IS NOT DEFINED"
MOVE = "action==move"
PUT = "action==put"
ACCEPT = "action==accept"
REDUCT = "action==reduct"
NODE = "type_is_node"
LEAF = "type_is_leaf"
LR_TABLE_FILE = "LR_table.txt"
REDUCTIONS_FILE = "reductions.txt"